spring:
  application:
    name: LLMentor_SpringAI
  ai:
#    alibaba:
#      mem0:
#        client:
#          base-url: http://127.0.0.1:8888
#          timeout-seconds: 120
#        server:
#          version: v1.0.0
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen:0.5b
    dashscope:
      api-key: @dashscope.api.key@
      chat:
        options:
#          model: qwen3.7-max
          model: glm-5.1
      memory:
        repository:
          jdbc:
            platform: mysql
            initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai_db2?useUnicode=true&characterEncoding=UTF-8  # 记得改成你自己的
    username: root  # 记得改成你自己的
    password: 123456  # 记得改成你自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      continue-on-error: true  # SQL初始化失败时继续启动
server:
  port: 8000